---
title: A FAIR and project-oriented template for open science data workflows
author:
  - name: Kauê de Sousa
    email: k.desousa@cgiar.org
    affiliation: a,b
    correspondingauthor: true
  - name: Marie-Angélique Laporte
    email: m.a.laporte@cgiar.org
    affiliation: c
address:
  - code: a
    organization: Digital Inclusion, Bioversity International
    city: Montpellier
    country: France
  - code: b
    organization: Department of Agricultural Sciences, University of Inland Norway
    city: Hamar
    country: Norway
  - code: c
    organization: Performance Innovation and Strategic Analysis for Impact (PISA4), Bioversity International
    city: Montpellier
    country: France
abstract: |
  Managing research data in accordance with the FAIR principles (Findable, Accessible, Interoperable, and Reusable) is essential for ensuring transparency, reproducibility, and effective scientific collaboration [@Wilkinson2016]. Reproducibility, the ability to repeat an analysis, and replicability, the ability to repeat an experiment under similar conditions [@Stevens2017], are foundational to trustworthy and collaborative science [@Powers2019; @Munafo2017]. These practices enable researchers to revisit analyses after extended periods and allow peers to verify results or generate new insights from existing data. In this context, we present a structured and reusable repository template specifically designed to support FAIR data workflows and promote both reproducibility and replicability across research projects.
keywords: 
 - data management
 - metadata
 - FAIR principles
 - reproducibility
 - open science
journal: "CGSpace"
date: "`r Sys.Date()`"
linenumbers: false
numbersections: false
bibliography: paper.bib
classoption: 3p, authoryear 
output: 
  rticles::elsevier_article:
    keep_tex: false
---

# Suggested citation

> de Sousa, K.; Laporte, M.-A. (2025) A FAIR and project-oriented template for open science data workflows. <https://hdl.handle.net/10568/174310>.

\pagebreak

# Statement of need

Data-driven research faces several challenges, including inadequate data documentation, inconsistent structure, and poor reproducibility [@Wilkinson2016; @Munafo2017]. Researchers often struggle with these aspects, lacking practical examples or accessible tools. To address these issues, we created a project-oriented, easy-to-use data template. It streamlines metadata management, facilitates reproducibility, and ensures alignment with FAIR principles.

# Repository structure

The template repository includes clear, intuitive folder structures and essential resources.

```text
template-repo-data-analysis/
|-- data/                                       # Anonimized raw and cleaned datasets
|-- docs/                                       # Reports or additional documentation
|-- metadata/                                   # Metadata files and templates
|    |-- project-metadata.xlsx                  # Project metadata
|    |-- project-metadata.json                  # Project metadata for DataCite
|    |-- example-metadata-data-mip-uganda.csv   # Description of the dataset (example)
|    |-- README.md    
|-- output/                                     # Model results, figures, tables
|-- script/                                     # Data analysis scripts
|-- .gitignore                                  # List of files to exclude from Git
|-- LICENSE                                     # License stablishing the rights to use
|-- CITATION.cff                                # Used by Zenodo to generate citation
|-- template-repo-data-analysis.Rproj           # RStudio file to set up the environment 
|-- README.md                                   # Project overview
```

# Key features

-   FAIR-aligned metadata: Comprehensive metadata files (.xlsx, .json) aligned with Zenodo (<https://zenodo.org>) and DataCite [@RobinsonGarcia2017] schemas.
-   Automated workflows: R scripts [@CRAN] to validate and convert metadata, ensuring consistent quality.
-   Citation integration: A CITATION.cff file for automatic citation generation.
-   Reproducibility: Scripts and clear instructions ensure any researcher can reproduce results.
-   Open and collaborative: Open licensing (CC BY 4.0, <https://creativecommons.org>) promotes collaboration, reuse, and attribution.

# Implementation and usage

Researchers can easily adopt this repository by:

1.  Cloning the repository from GitHub (<https://github.com/AgrDataSci/template-repo-data-analysis>).
2.  Adding their data and performing their analysis.
3.  Filling in the provided project-metadata.xlsx template.
4.  Running provided R scripts for validation and metadata generation.
5.  Publishing via integrated platforms like Zenodo for long-term archiving and DOI assignment.

# Conclusion

Adopting structured, FAIR-aligned workflows can significantly enhance reproducibility, collaboration, and transparency in research. This template provides a practical starting point, promoting best practices from the outset of research projects.

# Acknowledgments

This work has been supported by the projects 1000FARMS (INV-031561) funded by the Gates Foundation, and BOLD Work Package 7 (Crop Trust Ref: CONT-1522) funded by the Norwegian Agency for Development Cooperation (Norad) through The Global Crop Diversity Trust.

# References
